Repository guyidk/BookTrack_DevOps_Project, pull requests merged in 2024-11, with the labels that each got.

#57 Implement Add Book Feature with Validation and Confirmation
  public/css/style.css
  public/index.html
  public/js/Add-Book.js
  utils/Add-BookUtils.js
Labels: frontend, backend, error-handeling, validation

#58 Revert "Implement Add Book Feature with Validation and Confirmation"
  public/css/style.css
  public/index.html
  public/js/Add-Book.js
  utils/Add-BookUtils.js
Labels: bug

#60 Added some final adjustments code
  public/css/style.css
  public/index.html
  public/js/Add-Book.js
  utils/Add-BookUtils.js
Labels: enhancement

#64 Fixed and optimised add-book form layout in order to have a neat look and an intuitive form
  public/css/add-book.css
  public/css/style.css
  public/index.html
Labels: bug, enhancement

#66 Fixed confirmation alert errors while adding book and renamed own files for consistent naming convention across repository.
  index.js
  public/css/add-book.css
  public/css/style.css
  public/index.html
  public/js/addBook.js
  utils/addBookUtils.js
Labels: enhancement, error-handeling

#73 Renamed files and added comments
  models/Books.js
  public/css/addBook.css
  public/index.html
  public/js/addBook.js
  utils/addBookUtils.js
Labels: documentation, frontend, backend

#77 Renamed files for consistency
  index.js
  public/index.html
  public/js/update-book.js
  utils/update-book-util.js
Labels: frontend, backend

#76 Renamed files as per revised naming convention
  index.js
  public/css/add-book.css
  public/index.html
  public/js/add-book.js
  utils/add-book-util.js
Labels: documentation, frontend, backend

#78 Changed getBook.js to get-book.js and getBookUtil.js to get-book-util.js
  index.js
  public/index.html
  public/js/get-book.js
  utils/get-book-utils.js
Labels: enhancement

#79 Rectified an error in index.js that happened during simultaneous merges from other collaborators
  index.js
Labels: documentation, backend

#83 Updated the validation and alert message for ISBN number
  public/js/add-book.js
Labels: enhancement, frontend, validation

#84 Renamed models' files and updated the relevant codes
  index.js
  models/book.js
  models/borrow-transaction.js
  utils/add-book-util.js
  utils/add-transaction-util.js
  utils/get-book-utils.js
  utils/update-book-util.js
Labels: documentation

#91 handle book_id when exist
  utils/add-transaction-util.js
Labels: enhancement

#93 Shorten query length limit from 100 to 50 characters
  public/js/search-books.js
  utils/search-book-util.js
Labels: enhancement, error-handeling

#96 Added validations for Image size and (Title and author) character limits
  public/js/add-book.js
Labels: frontend, validation

#97 Removed irrelevant Comment
  utils/search-book-util.js
Labels: enhancement

#99 Fixed a minor error related to clearing form
  public/index.html
  public/js/add-book.js
Labels: bug

#101 Removed Special Character Validation due to Create and Update Functions Allowing it
  index.js
  public/js/search-books.js
  utils/get-book-util.js
  utils/search-book-util.js
Labels: frontend, backend, validation

#102 Changed the error message for empty or whitespace query
  public/js/search-books.js
Labels: backend, error-handeling, validation
